### PR TITLE
license revisions

### PR DESCRIPTION
**Pull request by jesseposner**
This is a first draft of my suggested revisions to the license. I have some additional revisions to the governance and proposal process sections that I will submit later today. We also need to clarify the "Base Award" definitions for the Royalty Tokens.

### CODE REVIEW

**Comment by jesseposner** [comment]
I removed the vision, values, proposal process, and hall of shame sections because they represent governance policies of the core contributors that I believe are better included in a separate document, rather than the legal agreement itself. This is for two primary reasons: (1) so that the legal agreement is focused strictly on legally binding obligations and (2) so that policies can be more easily changed as the project evolves.

**Comment by jesseposner** [comment]
This draft uses a Bitcoin address for payment of royalties for two reasons: (1) otherwise a bank account will be required, which will either require the core contributors to form a legal entity to own the bank account, or rely on a bank account of a single individual, which presents trust issues and (2) a Bitcoin address provides (A) a public record for accountability, (B) shared authority of the core contributors by means of multi-signature authorizations for royalty distributions to contributors, and (C) automated distribution of royalties to contributors by means of smart contracts.

**Comment by jesseposner** [comment]
The "Base Award" needs to be clarified, but I'm not sure what is meant by "Minor Open Contribution" and "Open Contribution." I'm assuming "Core Contributor hourly rate" applies to contributions by core contributors.

**Comment by aquabu** [comment]
I'm merging this. Let's track questions as github issues. There will be more issues from various reviewers.

**Pull request merged**
